# Base image
FROM node:14-alpine

# Dependencies
COPY ./ ./
RUN npm install

# Default command
CMD ["npm", "start"]


### Version 2 ###
# # Base image
# FROM node:14-alpine

# # Dependencies
# RUN npm install

# # Default command
# CMD ["npm", "start"]


### Version 1 ###
# # Base image
# FROM alpine

# # Dependencies
# RUN npm install

# # Default command
# CMD ["npm", "start"]
